'use client';

import { Check, Mail, Download, X } from 'lucide-react';
import { useState, useEffect } from 'react';
import confetti from 'canvas-confetti';
import jsPDF from 'jspdf';

interface BookingConfirmationProps {
    tripDetails: {
        destination: string;
        departureDate: string;
        returnDate?: string;
        flight: any;
        hotel: any;
        currency: string;
        totalCost: number;
    };
    onClose: () => void;
}

export default function BookingConfirmation({ tripDetails, onClose }: BookingConfirmationProps) {
    const [showEmailForm, setShowEmailForm] = useState(false);
    const [gdprConsent, setGdprConsent] = useState(false);
    const [sending, setSending] = useState(false);
    const [sent, setSent] = useState(false);

    useEffect(() => {
        // Celebration confetti!
        const duration = 3 * 1000;
        const animationEnd = Date.now() + duration;

        const randomInRange = (min: number, max: number) => {
            return Math.random() * (max - min) + min;
        };

        const interval = setInterval(() => {
            const timeLeft = animationEnd - Date.now();

            if (timeLeft <= 0) {
                return clearInterval(interval);
            }

            confetti({
                particleCount: 3,
                angle: randomInRange(55, 125),
                spread: randomInRange(50, 70),
                origin: { x: randomInRange(0.1, 0.9), y: Math.random() - 0.2 }
            });
        }, 50);

        return () => clearInterval(interval);
    }, []);

    const generatePDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(79, 70, 229); // Indigo
        doc.text('Project Voyager', 20, 20);
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text('Travel Itinerary (Demo Booking)', 20, 28);

        // Booking Confirmation
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Booking Confirmed!', 20, 45);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('This is a demonstration booking. No payment has been processed.', 20, 52);

        // Trip Details
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Trip Details', 20, 65);

        doc.setFontSize(10);
        doc.text(`Destination: ${tripDetails.destination}`, 20, 75);
        doc.text(`Departure: ${new Date(tripDetails.departureDate).toLocaleDateString('en-GB')}`, 20, 82);
        if (tripDetails.returnDate) {
            doc.text(`Return: ${new Date(tripDetails.returnDate).toLocaleDateString('en-GB')}`, 20, 89);
        }

        // Flight Details
        doc.setFontSize(14);
        doc.text('Flight', 20, 105);
        doc.setFontSize(10);
        doc.text(`Airline: ${tripDetails.flight.airline}`, 20, 115);
        doc.text(`Route: ${tripDetails.flight.route}`, 20, 122);
        doc.text(`Time: ${tripDetails.flight.time}`, 20, 129);
        doc.text(`Class: ${tripDetails.flight.class}`, 20, 136);
        doc.text(`Price: ${tripDetails.currency}${tripDetails.flight.price}`, 20, 143);

        // Hotel Details
        doc.setFontSize(14);
        doc.text('Hotel', 20, 160);
        doc.setFontSize(10);
        doc.text(`Name: ${tripDetails.hotel.name}`, 20, 170);
        doc.text(`Location: ${tripDetails.hotel.location}`, 20, 177);
        doc.text(`Rating: ${tripDetails.hotel.rating}/5.0`, 20, 184);
        doc.text(`Price: ${tripDetails.currency}${tripDetails.hotel.price} per night`, 20, 191);

        // Total
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text(`Total Cost: ${tripDetails.currency}${tripDetails.totalCost}`, 20, 210);

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Project Voyager - Demo System', 20, 280);
        doc.text('No actual booking has been made. This is for demonstration purposes only.', 20, 285);

        doc.save(`trip-${tripDetails.destination}-${Date.now()}.pdf`);
    };

    const sendEmail = async () => {
        if (!gdprConsent) {
            alert('Please consent to data processing to send the email.');
            return;
        }

        setSending(true);
        try {
            const response = await fetch('/api/send-booking-email', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    tripDetails,
                    gdprConsent: true
                })
            });

            if (response.ok) {
                setSent(true);
                setTimeout(() => setShowEmailForm(false), 2000);
            } else {
                alert('Failed to send email. Please try again.');
            }
        } catch (error) {
            alert('Error sending email. Please try again.');
        } finally {
            setSending(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
                <div className="p-8">
                    {/* Success Header */}
                    <div className="text-center mb-6">
                        <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 rounded-full mb-4">
                            <Check className="h-8 w-8 text-green-600" />
                        </div>
                        <h2 className="text-3xl font-bold text-slate-900 mb-2">
                            Success! Your Trip Has Been Booked
                        </h2>
                        <p className="text-slate-600">
                            (Demo Mode - No Payment Taken)
                        </p>
                    </div>

                    {/* Trip Summary */}
                    <div className="bg-indigo-50 rounded-lg p-6 mb-6">
                        <h3 className="font-bold text-lg text-indigo-900 mb-3">Trip Summary</h3>
                        <div className="space-y-2 text-sm">
                            <p><strong>Destination:</strong> {tripDetails.destination}</p>
                            <p><strong>Departure:</strong> {new Date(tripDetails.departureDate).toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                            {tripDetails.returnDate && (
                                <p><strong>Return:</strong> {new Date(tripDetails.returnDate).toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                            )}
                            <p><strong>Flight:</strong> {tripDetails.flight.airline} - {tripDetails.flight.time}</p>
                            <p><strong>Hotel:</strong> {tripDetails.hotel.name} ({tripDetails.hotel.rating}★)</p>
                            <p className="text-lg font-bold text-indigo-900 mt-3">
                                <strong>Total:</strong> {tripDetails.currency}{tripDetails.totalCost}
                            </p>
                        </div>
                    </div>

                    {/* Action Buttons */}
                    <div className="space-y-3">
                        <button
                            onClick={generatePDF}
                            className="w-full flex items-center justify-center px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors font-medium"
                        >
                            <Download className="h-5 w-5 mr-2" />
                            Download PDF Itinerary
                        </button>

                        {!showEmailForm ? (
                            <button
                                onClick={() => setShowEmailForm(true)}
                                className="w-full flex items-center justify-center px-6 py-3 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 transition-colors font-medium"
                            >
                                <Mail className="h-5 w-5 mr-2" />
                                Email Itinerary
                            </button>
                        ) : (
                            <div className="border border-slate-200 rounded-lg p-4 space-y-3">
                                <h4 className="font-medium text-slate-900">Email Itinerary</h4>
                                <p className="text-sm text-slate-600">
                                    Send booking details to: <strong>nicola@empowervaservices.co.uk</strong>
                                </p>

                                <label className="flex items-start text-sm">
                                    <input
                                        type="checkbox"
                                        checked={gdprConsent}
                                        onChange={(e) => setGdprConsent(e.target.checked)}
                                        className="mt-1 mr-2 h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-slate-300 rounded"
                                    />
                                    <span className="text-slate-600">
                                        I consent to my travel details being processed and sent via email for demonstration purposes.
                                        This data will not be stored or used for any other purpose. (GDPR Compliant)
                                    </span>
                                </label>

                                <div className="flex gap-2">
                                    <button
                                        onClick={sendEmail}
                                        disabled={!gdprConsent || sending || sent}
                                        className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium text-sm"
                                    >
                                        {sending ? 'Sending...' : sent ? '✓ Sent!' : 'Send Email'}
                                    </button>
                                    <button
                                        onClick={() => setShowEmailForm(false)}
                                        className="px-4 py-2 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 transition-colors font-medium text-sm"
                                    >
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        )}

                        <button
                            onClick={onClose}
                            className="w-full flex items-center justify-center px-6 py-3 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 transition-colors font-medium"
                        >
                            <X className="h-5 w-5 mr-2" />
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
